"""Fixed JD interpretation, aliases, feature names, and scoring weights."""

from __future__ import annotations

JD_QUERY = """
Senior AI Engineer founding team Redrob AI production embeddings retrieval ranking
candidate matching hybrid search vector database BM25 semantic search LLM reranking
Python evaluation framework NDCG MRR MAP A/B testing product engineering applied
machine learning NLP information retrieval recommender search systems shipped users scale
similar items neural representations context aware conversational system personalization
candidate fit talent matching marketplace relevance search concept_retrieval_system
concept_vector_database concept_rag_system concept_recommendation_system concept_evaluation.
"""

IMPORTANT_PHRASES = {
    "a/b testing",
    "ann search",
    "candidate fit",
    "candidate matching",
    "context aware",
    "dense retrieval",
    "hybrid search",
    "information retrieval",
    "learning to rank",
    "neural representations",
    "prompt engineering",
    "recommendation system",
    "search relevance",
    "semantic search",
    "similar items",
    "vector database",
    "vector representations",
    "vector search",
}

SEMANTIC_CONCEPTS = {
    "retrieval_system": [
        "find similar",
        "similar items",
        "similar candidates",
        "semantic search",
        "search relevance",
        "relevance search",
        "nearest neighbor",
        "dense retrieval",
        "neural retrieval",
        "retrieval system",
    ],
    "vector_database": [
        "faiss",
        "pinecone",
        "weaviate",
        "qdrant",
        "milvus",
        "pgvector",
        "vector store",
        "vector db",
        "vector database",
        "vector search",
        "ann search",
        "hnsw",
    ],
    "rag_system": [
        "context aware conversational",
        "knowledge grounded",
        "grounded generation",
        "retrieval augmented",
        "llm with search",
        "chatbot with search",
        "conversational system",
        "langchain",
        "llamaindex",
        "agentic",
    ],
    "recommendation_system": [
        "recommendation system",
        "recommender",
        "personalization",
        "personalized feed",
        "relevant items",
        "ranking feed",
        "matching engine",
        "candidate fit",
        "talent matching",
    ],
    "evaluation": [
        "ndcg",
        "mrr",
        "map",
        "precision at",
        "recall at",
        "offline evaluation",
        "online evaluation",
        "a/b testing",
        "ranking metrics",
    ],
}

FEATURE_NAMES = [
    "core_skill_match",
    "jd_keyword_coverage_score",
    "nice_skill_match",
    "skill_depth_score",
    "endorsement_trust",
    "assessment_score_avg",
    "disqualifier_skill_flag",
    "keyword_stuffer_flag",
    "github_signal",
    "product_company_ratio",
    "consulting_only_flag",
    "ir_ranking_experience",
    "production_evidence",
    "title_match_score",
    "senior_title_held",
    "career_trajectory_score",
    "scale_signal",
    "code_writing_recent",
    "yoe_fit_score",
    "education_score",
    "ml_ai_tenure_score",
    "open_source_signal",
    "availability_score",
    "engagement_score",
    "responsiveness_score",
    "interview_reliability",
    "profile_quality",
    "notice_period_score",
    "location_score",
    "relocation_willing",
    "backend_depth_score",
    "data_bi_depth_score",
    "hyre_similarity",
]

BASE_FEATURE_WEIGHTS = {
    "bm25_score": 0.10,
    "core_skill_match": 0.15,
    "nice_skill_match": 0.04,
    "skill_depth_score": 0.06,
    "endorsement_trust": 0.02,
    "assessment_score_avg": 0.02,
    "github_signal": 0.02,
    "product_company_ratio": 0.09,
    "ir_ranking_experience": 0.12,
    "production_evidence": 0.13,
    "senior_title_held": 0.04,
    "career_trajectory_score": 0.07,
    "scale_signal": 0.03,
    "code_writing_recent": 0.04,
    "yoe_fit_score": 0.06,
    "education_score": 0.02,
    "ml_ai_tenure_score": 0.04,
    "open_source_signal": 0.01,
    "location_score": 0.05,
    "relocation_willing": 0.01,
    "notice_period_score": 0.01,
}

MUST_HAVE_SKILLS = {
    "embeddings_retrieval": [
        "sentence-transformers",
        "sentence transformers",
        "openai embeddings",
        "bge",
        "e5",
        "embedding",
        "embeddings",
        "text embedding",
        "dense retrieval",
        "semantic search",
        "bi-encoder",
        "dual encoder",
        "vector representations",
    ],
    "vector_database": [
        "pinecone",
        "weaviate",
        "qdrant",
        "milvus",
        "faiss",
        "opensearch",
        "elasticsearch",
        "pgvector",
        "chroma",
        "vector search",
        "vector database",
        "vector store",
        "vector db",
        "ann",
        "ann search",
        "hnsw",
        "approximate nearest neighbor",
    ],
    "ranking_information_retrieval": [
        "ranking",
        "retrieval",
        "information retrieval",
        "learning to rank",
        "ltr",
        "reranking",
        "re-ranking",
        "cross-encoder",
        "recommendation system",
        "recommender",
        "search relevance",
        "relevance ranking",
        "ndcg",
        "mrr",
        "map",
        "precision@k",
        "recall@k",
    ],
    "llm_production": [
        "llm",
        "large language model",
        "genai",
        "generative ai",
        "agents",
        "agentic",
        "prompt engineering",
        "langchain",
        "llamaindex",
        "rag",
        "retrieval augmented generation",
        "fine-tuning",
        "fine tuning",
        "lora",
        "qlora",
        "peft",
        "instruction tuning",
    ],
    "python_ml_engineering": [
        "python",
        "pytorch",
        "tensorflow",
        "sklearn",
        "scikit-learn",
        "huggingface",
        "transformers",
        "numpy",
        "pandas",
        "xgboost",
        "lightgbm",
        "fastapi",
        "flask",
    ],
    "eval_frameworks": [
        "ndcg",
        "mrr",
        "map",
        "mean average precision",
        "a/b test",
        "ab test",
        "a/b testing",
        "offline evaluation",
        "online evaluation",
        "benchmark",
        "ranking metrics",
        "retrieval metrics",
    ],
}

MUST_HAVE_WEIGHTS = {
    "embeddings_retrieval": 0.25,
    "vector_database": 0.20,
    "ranking_information_retrieval": 0.25,
    "llm_production": 0.12,
    "python_ml_engineering": 0.12,
    "eval_frameworks": 0.06,
}

NICE_TO_HAVE_SKILLS = {
    "lora_finetuning": ["lora", "qlora", "peft", "fine-tuning llms", "finetuning"],
    "learning_to_rank": ["xgboost", "lightgbm", "ltr", "learning to rank", "lambdamart"],
    "distributed_systems": ["spark", "kafka", "flink", "ray", "dask", "distributed"],
    "marketplace_hrtech": ["hr-tech", "hr tech", "recruiting", "talent", "marketplace"],
    "open_source": ["github", "open source", "open-source", "contributed", "maintainer"],
}

PRODUCT_COMPANIES = {
    "cred",
    "flipkart",
    "swiggy",
    "zomato",
    "razorpay",
    "paytm",
    "phonepe",
    "meesho",
    "freshworks",
    "zoho",
    "ola",
    "google",
    "amazon",
    "microsoft",
    "apple",
    "adobe",
    "linkedin",
    "netflix",
    "uber",
    "meta",
    "openai",
    "anthropic",
    "databricks",
    "atlassian",
    "shopify",
    "stripe",
    "twilio",
    "nvidia",
    "bytedance",
    "samsung",
    "intel",
    "hooli",
    "initech",
    "globex inc",
    "stark industries",
    "wayne enterprises",
    "acme corp",
    "dunder mifflin",
}

PRODUCT_INDUSTRIES = {
    "software",
    "fintech",
    "saas",
    "ecommerce",
    "e-commerce",
    "edtech",
    "healthtech",
    "gaming",
    "marketplace",
    "ai",
    "ml",
    "data",
    "platform",
}

SERVICES_COMPANIES = {
    "tcs",
    "infosys",
    "wipro",
    "accenture",
    "cognizant",
    "capgemini",
    "mindtree",
    "hcl",
    "tech mahindra",
}

PREFERRED_INDIAN_LOCATIONS = {
    "pune",
    "noida",
    "delhi",
    "ncr",
    "gurgaon",
    "gurugram",
    "mumbai",
    "hyderabad",
    "bangalore",
    "bengaluru",
}

TARGET_TITLE_WEIGHTS = {
    "lead ai engineer": 1.0,
    "staff machine learning engineer": 1.0,
    "senior machine learning engineer": 1.0,
    "senior ai engineer": 1.0,
    "machine learning engineer": 0.95,
    "ml engineer": 0.95,
    "applied ml engineer": 0.95,
    "recommendation systems engineer": 0.95,
    "search engineer": 0.95,
    "senior nlp engineer": 0.9,
    "nlp engineer": 0.88,
    "senior data scientist": 0.78,
    "data scientist": 0.72,
    "data engineer": 0.65,
    "backend engineer": 0.58,
    "software engineer": 0.52,
    "cloud engineer": 0.42,
    "devops engineer": 0.38,
    "full stack developer": 0.34,
    "java developer": 0.28,
    ".net developer": 0.25,
    "frontend engineer": 0.18,
    "mobile developer": 0.16,
}

NON_TARGET_TITLES = {
    "marketing manager",
    "hr manager",
    "accountant",
    "graphic designer",
    "content writer",
    "sales executive",
    "civil engineer",
    "mechanical engineer",
    "customer support",
    "operations manager",
}

# JD explicitly devalues "recent (<12mo) LangChain-to-OpenAI" work and "framework
# enthusiasts". These are the wrapper/framework signals; note RAG is intentionally
# excluded (it is legitimate systems work), only the thin-wrapper tells are here.
LLM_WRAPPER_TERMS = {
    "langchain",
    "llamaindex",
    "llama index",
    "prompt engineering",
    "prompt chaining",
}

CV_SPEECH_ROBOTICS_TERMS = {
    "image classification",
    "computer vision",
    "opencv",
    "speech recognition",
    "tts",
    "text to speech",
    "gan",
    "gans",
    "robotics",
}

IR_RANKING_SIGNALS = {
    "ranking",
    "retrieval",
    "search",
    "recommendation",
    "recommender",
    "ranker",
    "indexing",
    "similarity search",
    "vector search",
    "semantic search",
    "relevance",
    "recall",
    "precision",
    "ndcg",
    "mrr",
    "bm25",
    "tf-idf",
}

PRODUCTION_SIGNALS = {
    "shipped",
    "deployed",
    "production",
    "launched",
    "users",
    "latency",
    "throughput",
    "serving",
    "inference",
    "monitoring",
    "on-call",
    "real-time",
    "a/b",
    "ab test",
    "low latency",
    "high throughput",
    "production system",
    "production ml",
}

SCALE_SIGNALS = {
    "million",
    "billion",
    "petabyte",
    "terabyte",
    "100k",
    "1m",
    "10m",
    "at scale",
    "high throughput",
    "low latency",
    "500gb",
}

PURE_RESEARCH_SIGNALS = {
    "research lab",
    "academic",
    "arxiv",
    "paper",
    "publication",
    "dissertation",
    "postdoc",
    "professor",
    "university research",
}

CODE_WRITING_SIGNALS = {
    "python",
    "implemented",
    "built",
    "coded",
    "developed",
    "microservice",
    "production code",
    "spring boot",
    "fastapi",
    "flask",
    "rest api",
    "grpc",
    "backend service",
}

OPEN_SOURCE_SIGNALS = {
    "open source",
    "open-source",
    "github",
    "maintainer",
    "contributed",
    "pull request",
    "public repo",
    "huggingface",
    "arxiv preprint",
}
