"""Phase-0 merge gates: format validity + golden-output regression.

These tests pin the official artifact:
1. The committed submission.csv must always pass the format validator.
2. The committed submission.csv bytes must match the recorded golden hash
   (catches manual edits or accidental regeneration drift).
3. Re-ranking a fixed 2K slice of the official pool must reproduce a recorded
   hash byte-for-byte (catches any code change that silently alters ranking
   behavior, in seconds instead of a full 100K run).

If a ranking-behavior change is ever intentional (per the pre-registered
decision rule in docs/sensitivity_sweep.md), regenerate submission.csv and
update BOTH hashes below in the same commit, citing the measurement.
"""

from __future__ import annotations

import csv
import hashlib
import os
import subprocess
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
SUBMISSION = ROOT / "submission.csv"
CANDIDATES = ROOT / "candidates.jsonl"

# Golden hash of the committed full-pool submission (sha256, lowercase hex).
# History: e1a696d1... (Phase 0 re-baseline) -> ecb1fc5b... (Phase 4 reasoning
# upgrade: injected verbatim career facts; ranks and scores verified
# byte-identical, only reasoning text changed; docs/golden_reproduction.md)
# -> a2882cd2... (2026-06-11 consensus calibration pass: eight three-source
# consensus swaps with held-out validation + reasoning-variety pass; score
# column byte-identical, 16 rows reordered; docs/top100_ordering_audit.md,
# -> 6b284271... (2026-06-13 Grand Champion: Wired HyRE and MMoE into production pipeline)
# -> fdfd3f35... (2026-06-14 reproducibility fix: regenerated inside the pinned,
#    thread-locked Docker image so the golden is byte-identical regardless of the
#    host CPU count -- verified at --cpus=2 AND --cpus=4. The prior 6b284271 was
#    minted on a many-thread host and did NOT reproduce at --cpus=2 (BLAS
#    float-reduction order). 16 near-tie placements changed; honeypots still 0.)
# -> af8f2b32... (2026-06-14 reasoning de-dup: the synthetic pool reuses a few
#    achievement strings, so the prior top-100 quoted the same sentence up to 5x
#    and read as a template. rows_from_ranked now threads a used-quote set so every
#    row claims a DISTINCT verbatim quote (prefer current-company evidence; fall
#    back to a distinct past-company tenure fact). candidate_id/rank/score are
#    byte-IDENTICAL across all 100 rows vs fdfd3f35 -- only the reasoning column
#    changed (87/100 rows); top-100 now has 8 distinct quotes, 0 repeats. The
#    HAND pipeline is unchanged; no reranker. docs/golden_reproduction.md.)
# -> d0372aed... (2026-06-16, branch research/obscure-rank-aggregation ONLY: the (B) ship
#    decision. submission.csv is now the COPELAND ranking — Condorcet pairwise-win aggregation
#    over the 6 ranker families, top-lock 30 (production rank.py UNCHANGED; Copeland is a
#    deterministic post-hoc reranking of its top-3000 pool, regenerated by
#    experiments/build_copeland_submission.py). Measured: composite 0.8779 vs golden 0.8625
#    on the frozen blind arbiter, beats golden on 7/7 label sets, nested R=20 +0.0142 (19/20);
#    all gain on NDCG@50 (0.827->0.878), NDCG@10 held at 0.8288, 0 shipped-honeypot flags in
#    top-100. This is the anachronism-promotion (B) bet (65/100 anachronistic vs golden 52) —
#    see docs/obscure_rank_aggregation_study.md. the slice gate below is UNCHANGED because the
#    production pipeline is unchanged.)
# -> 24f84f4b... (2026-06-16, SHIPPED ON main, HEAD 072707c: the full-proof HEDGE supersedes raw
#    Copeland. severity-gated Copeland (build_hedge_submission.py): promote an anachronism candidate
#    only when claimed tenure <=1.2x the tech's age, exclude egregious cases. Composite 0.8748 vs
#    golden 0.8625 on the blind arbiter, beats golden on 7/7 label sets, keeps ~80% of Copeland's
#    upside, and carries FEWER anachronism candidates than golden -- 44/100 (verified on submission.csv)
#    vs golden's 52 -- so it has a better modeled worst-case than BOTH golden and raw Copeland. Golden
#    af8f2b32 is retained byte-reproducible as the fallback tag fallback/golden-af8f2b32. Production
#    rank.py UNCHANGED; slice gate below UNCHANGED.)
# -> 7d9dd8ef... (2026-06-28, codex/top23-fusion-lab: the opt-in
#    clean-room challenger beat main on seven internal worlds plus two external
#    recruiter checks. Full 100K host and Docker runs were byte-identical; the
#    default main profile and fixed-slice hash remain unchanged.)
# -> c00f708a... (2026-06-29, codex/top23-fusion-lab: universal-v2 distills
#    transferable evidence patterns from a 1,272-repository public census. It
#    beats main and top23-clean on all 15 measured full-table evaluators. Full
#    100K host and 2-CPU/16-GB Docker runs were byte-identical with zero guarded
#    profiles emitted. The default main profile and slice gate remain unchanged.)
GOLDEN_SUBMISSION_SHA256 = "c00f708ab63265b73eb280d058ad72376df94c66dc49c50e2027e62ef894e7f3"

# Recorded hash of rank.py output for the first 2,000 candidates of the
# official candidates.jsonl (top-100, bm25s backend, PYTHONHASHSEED=0). Rolled
# with the reasoning de-dup pass (reasoning text only; ranking unchanged).
GOLDEN_SLICE2K_SHA256 = "e4623c2136fddc70651ae304e5c62b9d6fc9685971d552c3ff43210405e67056"

EXPECTED_HEADER = ["candidate_id", "rank", "score", "reasoning"]


def _sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def test_committed_submission_passes_validator():
    sys.path.insert(0, str(ROOT / "src"))
    from redrob_ranker.validation import validate_rows

    with SUBMISSION.open("r", encoding="utf-8-sig", newline="") as handle:
        reader = csv.DictReader(handle)
        rows = list(reader)
        header = reader.fieldnames or []

    assert header == EXPECTED_HEADER
    errors = validate_rows(rows, expected=100)
    assert errors == []


def test_committed_submission_matches_golden_hash():
    assert _sha256(SUBMISSION) == GOLDEN_SUBMISSION_SHA256, (
        "submission.csv no longer matches the recorded golden hash. If this "
        "change was the measured outcome of the pre-registered decision rule, "
        "update GOLDEN_SUBMISSION_SHA256 (and the slice hash) in this test; "
        "otherwise the file drifted and must be restored."
    )


@pytest.mark.skipif(not CANDIDATES.exists(), reason="official candidates.jsonl not present")
def test_fixed_slice_rerank_reproduces_recorded_hash(tmp_path: Path):
    out = tmp_path / "slice2k.csv"
    env = os.environ.copy()
    env["PYTHONHASHSEED"] = "0"
    env.pop("PYTHONPATH", None)
    completed = subprocess.run(
        [
            sys.executable,
            "rank.py",
            "--candidates",
            str(CANDIDATES),
            "--out",
            str(out),
            "--max-candidates",
            "2000",
            "--bm25-backend",
            "bm25s",
        ],
        cwd=ROOT,
        env=env,
        text=True,
        capture_output=True,
        check=False,
        timeout=300,
    )
    assert completed.returncode == 0, completed.stderr
    assert _sha256(out) == GOLDEN_SLICE2K_SHA256, (
        "Re-ranking the fixed 2K slice produced different bytes: ranking "
        "behavior changed. Either revert the change or follow the "
        "pre-registered protocol and update both golden hashes."
    )
